### ISSUE TITLE
User Runner is not created on Google Drive ( 1.371 )

### ISSUE THREAD

**Issue by dnguyendena** [DeNA/mobilize-server#48]
Hi Cassio,

I'm installing Mobilize on production cluster.
Everything was fine until I tried to create a user : 
bundle exec rake mobilize:add_user[xxxx,production]
xxxx has domain.com email and is a proper user of the Linux box.
No error occurred in the above statement. The user is created (I can see the user in console by User.first).
However, I could not see the Google Spreadsheet in GDrive of the owner.
I tried to go to the console and 
Runner.first.delete
User.first.runner

but it still did not create the Spreadsheet for me.
Finally, I went to google/gdrive.rb, and tried some command like
Gdrive.slot_worker_by_path( 'Runner_xxxx' )
without help.

Could you please explain me how to debug this problem?. Where is the code in which you create the GDrive Spreadsheet?

Thank you so much,
dnguyen

**Comment by c4ssio** [comment]
Hi Duc,

The Runner is actually created as part of the user.runner.gsheet command, so you can always find it by invoking that.

I've added a section to Troubleshooting called "Can't find Runner" let me know if that helps.

https://github.com/DeNA/mobilize-server/wiki/Administration:-Troubleshooting

**Comment by dnguyendena** [comment]
Thank you so much, Cassio.
I invoked user.runner.gsheet( owner_email@domain.com ) then it created the Spreadsheet for me : ).
I have successfully setup Mobilize for JP production cluster.

Thank you for your great help.
dnguyen

**Comment by c4ssio** [comment]
Glad to hear it! Closing issue.
